#!/bin/sh

USERNAME="u"
IP=10.101.46.252
#USERNAME="ubuntu"
#IP=192.168.56.102
MOUNTPOINT="$PWD/mnt"

usage() {
    echo "USAGE: debug-init mount [target IP]"
    echo "USAGE: debug-init umount"
    echo "USAGE: debug-init ssh [target IP]"
    exit 1
}

main() {
    # TODO: need to be executed with sudo

    if [ ! -e $MOUNTPOINT ]; then
        echo "ERROR: $MOUNTPOINT does not exist."
        exit 2
    fi
  
    if [ "$2" != "" ]; then
        IP=$2
    fi
    echo "Target IP: $IP"

    case $1 in
        mount)
            sshfs $USERNAME@$IP:/ "$MOUNTPOINT"
            #sshfs ubuntu@$IP:/ "$MOUNTPOINT" -o allow_other
            ;;
        umount)
            sudo umount "$MOUNTPOINT"
            ;;
        ssh)
            ssh $USERNAME@$IP
            ;;
        *)
            usage
            ;;
    esac
}

main $1 $2
